version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "npm"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "github-actions"
      include: "scope"
