x-playwright-service: &playwright-service
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
    - /app/node_modules
  deploy:
    resources:
      limits:
        memory: 2G
      reservations:
        memory: 1G
  environment:
    - CI=true

services:
  playwright-tests:
    <<: *playwright-service
    command: npx playwright test

  ui-tests:
    <<: *playwright-service
    command: npx playwright test --grep @ui --reporter=html

  api-tests:
    <<: *playwright-service
    command: npx playwright test --grep @api --reporter=html

  webtables-tests:
    <<: *playwright-service
    command: npx playwright test --grep @webTables --reporter=html

  chromium-tests:
    <<: *playwright-service
    command: npx playwright test --project=chromium --reporter=html

  firefox-tests:
    <<: *playwright-service
    command: npx playwright test --project=firefox --reporter=html
